version: '3.8'

services:
  # flickr:
  #   build: .
  #   image: flickr
  #   environment:
  #     - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
  #   ports:
  #     - '8085:8085'
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - .:/src
  #   networks:
  #     - node-network
  #
  # flickr-client:
  #   build: .
  #   image: flickr
  #   environment:
  #     - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
  #   ports:
  #     - '8085:8085'
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - .:/src
  #   networks:
  #     - node-network

  mongodb:
    container_name: flickr-db
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=flickr
      - MONGO_INITDB_ROOT_PASSWORD=flickr
      - MONGO_INITDB_DATABASE=flickr
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    networks:
      - node-network

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
    networks:
      - node-network

volumes:
  dbdata6:
  redis_volume_data:
  redis_insight_volume_data:


networks:
  node-network:
    driver: bridge
